version: '2'
services:
  ui:
    build: ./frontend
    ports:
      - '8501:8501'
    environment:
      - API_ENDPOINT=http://api:8000
    depends_on:
      - api
    image: taglertest/frontend-tagler
  api:
    build: .
    ports:
      - '8000:8000'
    environment:
      - ES_ENDPOINT=https://enterprise-search-deployment-1e36b1.es.uksouth.azure.elastic-cloud.com
      - ES_USER=elastic
      - ES_PASW=xYmUWIh8Ne5oBQCY6vEUrIlI
      - WIN=13.70.2.146
      - WIN_USER=tagler
      - WIN_PASW=Tagler@12345
    image: taglertest/backend-tagler
