version: '2'
services:
  ui:
    build: ./frontend
    command: bash -c "export API_ENDPOINT=http://127.0.0.1:8000 && streamlit run web_app.py --server.port=8501 --server.enableCORS=false --server.enableXsrfProtection=false"
    ports:
      - '8501:8501'
    depends_on:
      - api
  api:
    build: .
    ports:
      - '8000:8000'